<?php
namespace Pachel\TableAdmin\Models;

use \Pachel\dbClass\Callbacks\CallbackBase;
use \Pachel\dbClass\dataModel\dataModel;
use \Pachel\dbClass\dataModel\Traits\EqualMethods;
use \Pachel\dbClass\dataModel\Traits\EqMethods;
use \Pachel\dbClass\dataModel\Traits\LikeMethods;
use \Pachel\dbClass\dataModel\Traits\UpMethods;

/**
 * @method fajlokDataModel getById(int $id)
 * @method fajlokSelectCBclass select(array|object $where)
 * @method fajlokModelEqualSelect like()
 * @method fajlokModelEqualSelect equal()
 * @method fajlokModelEqSelect eq()
 * asda sd haskl dalksdjlaksjd lkasd
 * @method fajlokModelUpSelect up()
 * ...
 * @generated by dbClass 2026-10-06 21:50
 * @author Tóth László
 * @email pachel82@gmail.com
**/
class fajlokModel extends dataModel{
	/**
	* @var string $_primary A(z) "fajlok" tábla elsődleges kulcsa az adatbázisban
	*/
	protected $_primary = "id";

	/**
	* @var string $_tablename Az SQL tábla neve
	*/
	protected $_tablename = "fajlok";

	/**
	* @var array $_not_visibles A SELECT lekérdezésben láthatatlan mezők nevei
	*/
	protected $_not_visibles = [];

	/**
	* @var bool $_safemode Biztonságos mód a törléshez, ha ez true, akkor a mezőt is be kell állítani
	*/
	protected $_safemode = false;

	/**
	* @var string $_safefield A törléshez használt mező, ami a biztonságos törlésnél 1-es értéket vesz fel
	*/
	protected $_safefield = "deleted";
	//Az adatmodel osztály neve
	protected $_modelclass = fajlokDataModel::class;

	protected $_likeclass = fajlokModelLikeSelect::class;

    protected $_equalclass  = fajlokModelEqualSelect::class;

    protected $_eqclass  = fajlokModelEqSelect::class;

    protected $_upclass  = fajlokModelUpSelect::class;
}
/**
 * Primary ID ----------------------------------------
 * @property int $id
 * @property int $deleted
 * @property string $path
 * @property string $name
 * @property string $mime
 * @property string $inserted
 * @property string $updated
 * @property int $fid
 * @property string $table
 * @property int $id_users

*/
class fajlokDataModel extends \stdClass{

}

/**
 * @method fajlokDataModel[] id(int $id)
 * @method fajlokDataModel[] deleted(int $deleted)
 * @method fajlokDataModel[] path(string $path)
 * @method fajlokDataModel[] name(string $name)
 * @method fajlokDataModel[] mime(string $mime)
 * @method fajlokDataModel[] inserted(string $inserted)
 * @method fajlokDataModel[] updated(string $updated)
 * @method fajlokDataModel[] fid(int $fid)
 * @method fajlokDataModel[] table(string $table)
 * @method fajlokDataModel[] id_users(int $id_users)
 */
class fajlokModelEqualSelect extends CallbackBase {
    use EqualMethods;
}
/**
 * @method fajlokDataModel[] rows()
 * @method fajlokDataModel line()
 * @method mixed simple()
 * @method fajlokModelEqSelect id(int $id)
 * @method fajlokModelEqSelect deleted(int $deleted)
 * @method fajlokModelEqSelect path(string $path)
 * @method fajlokModelEqSelect name(string $name)
 * @method fajlokModelEqSelect mime(string $mime)
 * @method fajlokModelEqSelect inserted(string $inserted)
 * @method fajlokModelEqSelect updated(string $updated)
 * @method fajlokModelEqSelect fid(int $fid)
 * @method fajlokModelEqSelect table(string $table)
 * @method fajlokModelEqSelect id_users(int $id_users)
 */
class fajlokModelEqSelect extends CallbackBase {
    use EqMethods;
}
/**

 * @method mixed exec()
 * @method fajlokModelUpSelect where()
 * @method fajlokModelUpSelect id(int $id)
 * @method fajlokModelUpSelect deleted(int $deleted)
 * @method fajlokModelUpSelect path(string $path)
 * @method fajlokModelUpSelect name(string $name)
 * @method fajlokModelUpSelect mime(string $mime)
 * @method fajlokModelUpSelect inserted(string $inserted)
 * @method fajlokModelUpSelect updated(string $updated)
 * @method fajlokModelUpSelect fid(int $fid)
 * @method fajlokModelUpSelect table(string $table)
 * @method fajlokModelUpSelect id_users(int $id_users)
 */
class fajlokModelUpSelect extends CallbackBase {
    use UpMethods;
}

/**
 * @method fajlokDataModel[] path(string $path)
 * @method fajlokDataModel[] name(string $name)
 * @method fajlokDataModel[] mime(string $mime)
 * @method fajlokDataModel[] inserted(string $inserted)
 * @method fajlokDataModel[] updated(string $updated)
 * @method fajlokDataModel[] table(string $table)
 */
class fajlokModelLikeSelect extends CallbackBase {
    use LikeMethods;
}
/**
 * @method fajlokDataModel[] rows()
 * @method fajlokDataModel line()
 * @method mixed simple()
 */
abstract class fajlokSelectCBclass{

}